services:

  zeebe:
    image: camunda/zeebe:${CAMUNDA_CLOUD_VERSION:-8.0.0}
    container_name: zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
    environment:
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
    restart: always
    volumes:
      - zeebe:/usr/local/zeebe/data
      - ./zeebe-application.yml:/usr/local/zeebe/config/application.yaml
    networks:
      - camunda-cloud
    depends_on:
      - elasticsearch

  operate:
      image: camunda/operate:${CAMUNDA_CLOUD_VERSION:-8.0.0}
      container_name: operate
      ports:
        - "8081:8080"
      environment:
#        # For more information regarding configuration with Identity see: https://docs.camunda.io/docs/self-managed/operate-deployment/authentication/#iam
        - SPRING_PROFILES_ACTIVE=identity-auth
        - CAMUNDA_OPERATE_IDENTITY_ISSUER_URL=http://localhost:18080/auth/realms/camunda-platform
        - CAMUNDA_OPERATE_IDENTITY_ISSUER_BACKEND_URL=http://keycloak:8080/auth/realms/camunda-platform
        - CAMUNDA_OPERATE_IDENTITY_CLIENTID=operate
        - CAMUNDA_OPERATE_IDENTITY_CLIENTSECRET=XALaRPl5qwTEItdwCMiPS62nVpKs7dL7
        - CAMUNDA_OPERATE_IDENTITY_AUDIENCE=operate-api
        - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
        - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
        - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      networks:
        - camunda-cloud
        - identity-network
      depends_on:
        - elasticsearch

  tasklist:
      image: camunda/tasklist:${CAMUNDA_CLOUD_VERSION:-8.0.0}
      container_name: tasklist
      ports:
        - "8082:8080"
      environment:
        # For more information regarding configuration with IAM see: https://docs.camunda.io/docs/self-managed/tasklist-deployment/authentication/#iam
        - SPRING_PROFILES_ACTIVE=identity-auth
        - CAMUNDA_TASKLIST_IDENTITY_ISSUER_URL=http://localhost:18080/auth/realms/camunda-platform
        - CAMUNDA_TASKLIST_IDENTITY_ISSUER_BACKEND_URL=http://keycloak:8080/auth/realms/camunda-platform
        - CAMUNDA_TASKLIST_IDENTITY_CLIENTID=tasklist
        - CAMUNDA_TASKLIST_IDENTITY_CLIENTSECRET=XALaRPl5qwTEItdwCMiPS62nVpKs7dL7
        - CAMUNDA_TASKLIST_IDENTITY_AUDIENCE=tasklist-api
        - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
        - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
        - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
        - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_CLUSTERNAME=elasticsearch
        - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_PREFIX=zeebe-record
      networks:
        - camunda-cloud
        - identity-network
      depends_on:
        - elasticsearch

  optimize:
    # For more information see: https://docs.camunda.io/docs/self-managed/optimize-deployment/setup/
    image: camunda/optimize:${CAMUNDA_OPERATE_VERSION:-3.8.0-RC2}
    container_name: optimize
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=ccsm
      - CAMUNDA_OPTIMIZE_IDENTITY_ISSUER_URL=http://localhost:18080/auth/realms/camunda-platform
      - CAMUNDA_OPTIMIZE_IDENTITY_ISSUER_BACKEND_URL=http://keycloak:8080/auth/realms/camunda-platform
      - CAMUNDA_OPTIMIZE_IDENTITY_CLIENTID=optimize
      - CAMUNDA_OPTIMIZE_IDENTITY_CLIENTSECRET=XALaRPl5qwTEItdwCMiPS62nVpKs7dL7
      - CAMUNDA_OPTIMIZE_IDENTITY_AUDIENCE=optimize-api
      # Settings for Elasticsearch, etc.
      - OPTIMIZE_ELASTICSEARCH_HOST=elasticsearch
      - OPTIMIZE_ELASTICSEARCH_HTTP_PORT=9200
      - CAMUNDA_OPTIMIZE_SECURITY_AUTH_COOKIE_SAME_SITE_ENABLED=false
      - CAMUNDA_OPTIMIZE_ENTERPRISE=false
      - CAMUNDA_OPTIMIZE_ZEEBE_ENABLED=true
      - CAMUNDA_OPTIMIZE_ZEEBE_NAME=zeebe-record
      - CAMUNDA_OPTIMIZE_ZEEBE_PARTITION_COUNT=2
      - CAMUNDA_OPTIMIZE_SHARING_ENABLED=false
      - CAMUNDA_OPTIMIZE_UI_LOGOUT_HIDDEN=true
      - CAMUNDA_OPTIMIZE_API_AUDIENCE=optimize
      - OPTIMIZE_API_ACCESS_TOKEN=secret
    restart: on-failure
    networks:
      - camunda-cloud
      - identity-network

  identity:
    container_name: identity
    image: camunda/identity:8.0.0
    ports:
      - "8084:8081"
    environment:
      SERVER_PORT: 8081
      KEYCLOAK_URL: http://keycloak:8080/auth
      IDENTITY_AUTH_PROVIDER_BACKEND_URL: http://keycloak:8080/auth/realms/camunda-platform
      KEYCLOAK_INIT_OPTIMIZE_SECRET: XALaRPl5qwTEItdwCMiPS62nVpKs7dL7
      KEYCLOAK_INIT_OPTIMIZE_ROOT_URL: http://localhost:8090
      KEYCLOAK_INIT_OPERATE_SECRET: XALaRPl5qwTEItdwCMiPS62nVpKs7dL7
      KEYCLOAK_INIT_OPERATE_ROOT_URL: http://localhost:8081
      KEYCLOAK_INIT_TASKLIST_SECRET: XALaRPl5qwTEItdwCMiPS62nVpKs7dL7
      KEYCLOAK_INIT_TASKLIST_ROOT_URL: http://localhost:8082
      KEYCLOAK_USERS_0_USERNAME: "demo"
      KEYCLOAK_USERS_0_PASSWORD: "demo"
      KEYCLOAK_USERS_0_FIRST_NAME: "demo"
      KEYCLOAK_USERS_0_ROLES_0: "Identity"
      KEYCLOAK_USERS_0_ROLES_1: "Optimize"
      KEYCLOAK_USERS_0_ROLES_2: "Operate"
      KEYCLOAK_USERS_0_ROLES_3: "Tasklist"
    restart: on-failure
    networks:
      - identity-network
    depends_on:
      - keycloak

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:16.1.1
    ports:
      - "18080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    networks:
      - identity-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.16.2}
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    # cpu_count and mem_limit may not work or might be ignored by your version of docker-compose. Uncomment if desired and is supported by your version of docker-compose
#    cpu_count: 4
#    mem_limit: 2g
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cat/health | grep -q green" ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - camunda-cloud

volumes:
    zeebe:
    elastic:

networks:
  # Note there are two bridge networks. One for Zeebe and one for IAM. Operate, Tasklist, and Optimize use both
  camunda-cloud: { }
  identity-network: { }
